version: '3'

volumes:
  local_postgres_data: {}
  local_pgadmin_data: {}

services:
  postgres:
    container_name: attack_surface_service_local_postgres
    image: postgres:11.3
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  pgadmin:
    container_name: attack_surface_service_local_pgadmin
    image: dpage/pgadmin4
    volumes:
       - local_pgadmin_data:/root/.pgadmin
    depends_on:
      - postgres
    ports:
      - "5050:80"
    env_file:
      - ./.env
    restart: unless-stopped

  redis:
    image: redis:3.0
    ports:
      - "6379:6379"
